---
controller:
  serviceAccount:
    create: false
    name: ${service_account_name}
node:
  tolerateAllTaints: true
storageClasses:
  - name: "gp3"
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    volumeBindingMode: "WaitForFirstConsumer"
    reclaimPolicy: "Delete"
    allowVolumeExpansion: true
    parameters:
      type: "gp3"
      csi.storage.k8s.io/fstype: "ext4"
