apiVersion: apps/v1
kind: Deployment
{{/*apiVersion: argoproj.io/v1alpha1*/}}
{{/*kind: Rollout*/}}
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
    spec:
      serviceAccountName: hotelspecials-service-account
      volumes:
        - name: config-volume
          configMap:
            name: "xray-config"
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.app.name }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: hotelspecials-configmap
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: hotelspecials-configmap
            - name: DATABASE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: database_endpoint
                  name: hotelspecials-configmap
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: database_port
                  name: hotelspecials-configmap
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: database_username
                  name: hotelspecials-configmap
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: database_password
                  name: hotelspecials-configmap
            - name: JDBC_CONNECTION_STRING
              value: "jdbc:mysql://${DATABASE_ENDPOINT}:${DATABASE_PORT}/m2m?useSSL=false&autoReconnect=true"
            - name: JDBC_UID
              value: ${DATABASE_USERNAME}
            - name: JDBC_PWD
              value: ${DATABASE_PASSWORD}
            - name: TZ
              value: Asia/Seoul
        - name: xray-daemon
          image: amazon/aws-xray-daemon:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: xray-ingest
              containerPort: 2000
              protocol: UDP
            - name: xray-tcp
              containerPort: 2000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          # Volume mount for X-Ray Configuration.
          volumeMounts:
            - name: config-volume
              mountPath: /aws/xray
              readOnly: true
---
# Configuration for AWS X-Ray daemon.
apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
  namespace: hotelspecials
data:
  config.yaml: |-
    TotalBufferSizeMB: 24
    Socket:
      UDPAddress: "0.0.0.0:2000"
      TCPAddress: "0.0.0.0:2000"
    LocalMode: true
    Version: 2
    Logging:
      LogLevel: "debug"
