namespace:
  crate: false
  name: hotelspecials
app:
  name: hotelspecials
  build_number: 0
deployment:
  name: hotelspecials
  replicas: 2
image:
  repository: ${ECR_REPO_URI}
  tag: ${IMAGE_TAG}
container:
  port: 8080
service:
  name: hotelspecials-service
  type: NodePort
  port: 80
ingress:
  enabled: true
  name: hotelspecials-ingress
  certificate_arn: ${CERTIFICATE_ARN}
configmap:
  name: hotelspecials-configmap
  environment: dev
  database_endpoint: ${DATABASE_ENDPOINT}
  database_port: ${DATABASE_PORT}
  database_username: ${DATABASE_USERNAME}
  database_password: ${DATABASE_PASSWORD}
