apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-credentials
  namespace: ${namespace}
type: Opaque
data:
  username: ${username}  # Base64 encoded 'admin'
  apikey: ${apikey}  # Base64 encoded '08b7...'
