# Refer: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/cni-metrics-helper/values.yaml
env:
  AWS_CLUSTER_ID: ${cluster_name}
  AWS_VPC_K8S_CNI_LOGLEVEL: "DEBUG"

serviceAccount:
  name: ${service_account_name}
  annotations:
    eks.amazonaws.com/role-arn: ${service_account_role_arn}
