---
external_services:
  prometheus:
    url: "http://prometheus-server"
kiali_feature_flags:
  clustering:
    autodetect_secrets:
      enabled: false
deployment:
  replicas: 2
  ingress:
    enabled: true
    class_name: ""
    override_yaml:
      metadata:
        annotations:
          kubernetes.io/ingress.class: "alb"
          alb.ingress.kubernetes.io/scheme: "internet-facing"
          alb.ingress.kubernetes.io/target-type: "ip"
          alb.ingress.kubernetes.io/success-codes: "200,404,301,302"
          alb.ingress.kubernetes.io/group.name: "kaili"
          alb.ingress.kubernetes.io/group.order: "1"
      spec:
        rules:
          - http:
              paths:
                - path: "/kiali"
                  pathType: "Prefix"
                  backend:
                    service:
                      name: "kiali"
                      port:
                        number: 20001
