graph TD
    A[프론트엔드 사용자 인터페이스 분리 React.js 등] --> B[HotelSpecials 데이터베이스 스키마 전환]
    B --> C[HotelSpecials 백엔드 애플리케이션 마이그레이션 및 실행 EC2 -> EKS]
    C --> D[애플리케이션 트래픽 유입 중단]
    D --> E[HotelSpecials 데이터 마이그레이션]
    E --> F[ALB 요청 라우팅 설정]
    F --> G[프론트엔드 To 백엔드 접속 DNS를 ALB로 변경 최초 일회]
    G --> H[넓은 지역으로 DNS 전파가 확인되면 트래픽 유입 재개]
    H --> I[HotelSpecials 데이터의 SSOT 클라우드 전환 완료]
    I --> J[FlightSpecials 트래픽은 기존 온프레미스로 유입]
    J --> K[FlightSpecials 데이터베이스 스키마 전환]
    K --> L[FlightSpecials 서비스 마이그레이션 및 실행]
    L --> M[애플리케이션 트래픽 유입 중단]
    M --> N[FlightSpecials 데이터 마이그레이션]
    N --> O[ALB 요청 라우팅 설정]
    O --> P[애플리케이션 트래픽 유입 재개]
    P --> Q[FlightSpecials 데이터 SSOT 클라우드 전환 완료]

    style D fill:#FFA07A,stroke:#FF6347,stroke-width:2px,color:#000000
    style H fill:#98FB98,stroke:#32CD32,stroke-width:2px,color:#000000
    style M fill:#FFA07A,stroke:#FF6347,stroke-width:2px,color:#000000
    style P fill:#98FB98,stroke:#32CD32,stroke-width:2px,color:#000000
