graph TD
A[신규 인프라 구성] --> B[프론트엔드 사용자 인터페이스 분리 React.js 등]
B --> C[HotelSpecials 데이터베이스 스키마 전환]
C --> D[HotelSpecials 서비스 마이그레이션 및 구동]
D --> E[레거시 요청 ALB 라우팅 설정]
E --> F[애플리케이션 트래픽 유입 중단]
F --> G[HotelSpecials 데이터 마이그레이션]
G --> H[프론트엔드의 백엔드 접속 DNS를 ALB로 변경 - 최초 일회]
H --> I[넓은 지역으로 DNS 전파가 확인]
I --> J[애플리케이션 트래픽 유입 재개]
J --> K[HotelSpecials 데이터의 SSOT 클라우드 전환 완료 선언]
J --> L[FlightSpecials 트래픽은 기존 온프레미스로 유입]
L --> M[FlightSpecials 데이터베이스 스키마 전환]
M --> N[애플리케이션 트래픽 유입 중단]
N --> O[FlightSpecials 서비스 마이그레이션 및 구동]
O --> P[FlightSpecials 데이터 마이그레이션]
P --> Q[애플리케이션 트래픽 유입 재개]
Q --> R[FlightSpecials 데이터의 SSOT 클라우드 전환 완료 선언]
%%R1[점진적 전환]
%%R ---> R1
R -->|나머지 서비스 점진적 전환| M
X[전체 애플리케이션 및 데이터베이스의 클라우드 전환 완료 선언]
R --> X
K --> X

style F fill:#FFA07A,stroke:#FF6347,stroke-width:2px,color:#000000
style J fill:#98FB98,stroke:#32CD32,stroke-width:2px,color:#000000
style N fill:#FFA07A,stroke:#FF6347,stroke-width:2px,color:#000000
style Q fill:#98FB98,stroke:#32CD32,stroke-width:2px,color:#000000
